services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: okstal
      POSTGRES_USER: okstal
      POSTGRES_PASSWORD: okstal123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - nginx
    environment:
      - DATABASE_URL=postgresql://okstal:okstal123@db:5432/okstal

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    depends_on:
      - web

volumes:
  postgres_data:
